### ISSUE TITLE
Trouble with starting/initializing the MySQL server

### ISSUE THREAD

**Issue by jw51** [ISU-HPC/mysql#2]
Hi
I'm not sure whether this is an issue or if it's just me as I don't have much experience with singularity containers, but I would very very much appreciate any help/suggestions. 
I am trying to find orthologous groups of proteins using orthomcl (following the instructions on [this website](https://bioinformaticsworkbook.org/dataAnalysis/phylogenetics/00-finding-orthologs-uisng-orthoMCL.html) It doesn't have a question section, but it uses your images, so I'm going to give it a try here... 

I think everything goes well up until this step:
`singularity run instance://mysql`
Then I get output with quite some errors. 
`...  
2020-06-02T14:26:17.019022Z 1 [ERROR] InnoDB: Table `mysql`.`innodb_table_stats` not found.  
2020-06-02T14:26:17.020892Z 1 [ERROR] mysqld: The table 'plugin' is full  
2020-06-02T14:26:17.020993Z 1 [ERROR] 1114  The table 'plugin' is full  
2020-06-02T14:26:17.021124Z 0 [ERROR] Aborting  
...  
mysqld: Table 'mysql.plugin' doesn't exist  
2020-06-02T14:26:18.666918Z 0 [ERROR] Can't open the mysql.plugin table. Please run mysql_upgrade to create it.  
...  
2020-06-02T14:26:18.675370Z 0 [ERROR] Missing system table mysql.proxies_priv; please run mysql_upgrade to create it  
...  
2020-06-02T14:26:18.675496Z 0 [ERROR] Fatal error: Can't open and lock privilege tables: Table 'mysql.tables_priv' doesn't exist  
2020-06-02T14:26:18.675514Z 0 [ERROR] Fatal: can't initialize grant subsystem - 'Table 'mysql.tables_priv' doesn't exist'  
2020-06-02T14:26:18.675666Z 0 [ERROR] Aborting  
...`  

The mysql/var/lib/mysql directory contains the auto.cnf,  ib_buffer_pool,  ibdata1,  ib_logfile0, ib_logfile1 files and a mysql directory with the db.frm,  db.MYD,  db.MYI,  db.opt,  func.frm, func.MYD,  func.MYI,  user.frm,  user.MYD and user.MYI files.  

I have no idea what could have gone wrong or where these files (mysql.plugin, mysql.proxies_priv, mysql.tables_priv, ...) should be... Also I don't find/have the mysql_upgrade script that is mentioned as solution. 
Any help would be appreciated!

[I am an HPC user without root privileges]

**Comment by rgrandin** [comment]
What version of Singularity are you using?  I just confirmed that the instructions (see quick-start in this repo's REAME, as well as the expanded form linked at the top of the README: https://www.hpc.iastate.edu/guides/containers/mysql-server) work for Singularity 2.6.0.  

When using Singularity 3.5.2, however, I experience errors when mysql attempts to initialize itself.  (I'm looking into that now)

**Comment by jw51** [comment]
Hi. Yes I am using version 3.5.2, version 2.6.0 seems not to be available on our HPC and I also cannot install it...

**Comment by rgrandin** [comment]
Thanks.  I'll let you know what I find out.

**Comment by rgrandin** [comment]
It turns out that the errors I saw with singularity v3.5.2 was simply a bind-mount for temporary space.  That's probably unrelated to your issue.

Can you please try following the instructions at https://www.hpc.iastate.edu/guides/containers/mysql-server, and providing a copy of the output as you run the commands?  (e.g., go through the commands and then copy/paste from your terminal)  Seeing errors/warnings as they occur may be helpful.  That link is the instructions on which the bioinformatics workbook info is based, but it is a bit more complete on the initial setup steps.  In the first step, load the version of singularity you have available to you, but after that you should be able to follow the instructions as-is.

**Comment by jw51** [comment]
Thanks a lot for looking into this! 
Here is the output to the commands (I used singularity version 3.5.3-1.1.el7)

> $ singularity pull --name mysql.simg shub://ISU-HPC/mysql
> INFO:    Use image from cache

> $ curl https://raw.githubusercontent.com/ISU-HPC/mysql/master/my.cnf > ${HOME}/.my.cnf
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   108  100   108    0     0    226      0 --:--:-- --:--:-- --:--:--   226
> $ curl https://raw.githubusercontent.com/ISU-HPC/mysql/master/mysqlrootpw > ${HOME}/.mysqlrootpw
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100    64  100    64    0     0   1939      0 --:--:-- --:--:-- --:--:--  1939

> $ mkdir -p ${PWD}/mysql/var/lib/mysql ${PWD}/mysql/run/mysqld

> $ singularity instance start --bind ${HOME} --bind ${PWD}/mysql/var/lib/mysql/:/var/lib/mysql --bind ${PWD}/mysql/run/mysqld:/run/mysqld ./mysql.simg mysql
> INFO:    instance started successfully

If I run it with the dot between instance and start I get a usage error (the help output is printed).

> $ singularity run instance://mysql
> $VSC_HOME/.my.cnf already exists.  Using that version.
> $VSC_HOME/.mysqlrootpw already exists.  Using that version.
> Start mysqld
> _**Then automatically I get a new prompt(?)**_ $ 2020-06-05T20:18:36.172846Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
> 2020-06-05T20:18:36.178249Z 0 [Note] mysqld (mysqld 5.7.21) starting as process 25 ...
> 2020-06-05T20:18:36.204141Z 0 [Note] InnoDB: PUNCH HOLE support available
> 2020-06-05T20:18:36.204173Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
> 2020-06-05T20:18:36.204181Z 0 [Note] InnoDB: Uses event mutexes
> 2020-06-05T20:18:36.204187Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
> 2020-06-05T20:18:36.204194Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.3
> 2020-06-05T20:18:36.207052Z 0 [Note] InnoDB: Number of pools: 1
> 2020-06-05T20:18:36.211572Z 0 [Note] InnoDB: Using CPU crc32 instructions
> 2020-06-05T20:18:36.214242Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
> 2020-06-05T20:18:36.223309Z 0 [Note] InnoDB: Completed initialization of buffer pool
> 2020-06-05T20:18:36.225895Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setp
> riority().
> 2020-06-05T20:18:36.237929Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
> 2020-06-05T20:18:36.278254Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
> 2020-06-05T20:18:36.278664Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
> 2020-06-05T20:18:36.288909Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
> 2020-06-05T20:18:36.289983Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
> 2020-06-05T20:18:36.289999Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
> 2020-06-05T20:18:36.290361Z 0 [Note] InnoDB: Waiting for purge to start
> 2020-06-05T20:18:36.340662Z 0 [Note] InnoDB: 5.7.21 started; log sequence number 1213673
> 2020-06-05T20:18:36.341137Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
> 2020-06-05T20:18:36.342579Z 0 [Note] Plugin 'FEDERATED' is disabled.
> 2020-06-05T20:18:36.342675Z 0 [Note] InnoDB: Buffer pool(s) load completed at 200605 22:18:36
> mysqld: Table 'mysql.plugin' doesn't exist
> 2020-06-05T20:18:36.345326Z 0 [ERROR] Can't open the mysql.plugin table. Please run mysql_upgrade to create it.
> 2020-06-05T20:18:36.346728Z 0 [Warning] Gtid table is not ready to be used. Table 'mysql.gtid_executed' cannot be opened.
> 2020-06-05T20:18:36.346802Z 0 [Warning] Failed to set up SSL because of the following SSL library error: SSL context is not usable without certificate and pri
> vate key
> 2020-06-05T20:18:36.348261Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
> 2020-06-05T20:18:36.348305Z 0 [Note] IPv6 is available.
> 2020-06-05T20:18:36.348341Z 0 [Note]   - '::' resolves to '::';
> 2020-06-05T20:18:36.348355Z 0 [Note] Server socket created on IP: '::'.
> 2020-06-05T20:18:36.350519Z 0 [Warning] Failed to open optimizer cost constant tables
> 
> 2020-06-05T20:18:36.354935Z 0 [ERROR] Missing system table mysql.proxies_priv; please run mysql_upgrade to create it
> 2020-06-05T20:18:36.355012Z 0 [Warning] Can't open and lock time zone table: Table 'mysql.time_zone_leap_second' doesn't exist trying to live without them
> 2020-06-05T20:18:36.355045Z 0 [ERROR] Fatal error: Can't open and lock privilege tables: Table 'mysql.tables_priv' doesn't exist
> 2020-06-05T20:18:36.355052Z 0 [ERROR] Fatal: can't initialize grant subsystem - 'Table 'mysql.tables_priv' doesn't exist'
> 2020-06-05T20:18:36.355467Z 0 [ERROR] Aborting
> 
> 2020-06-05T20:18:36.355502Z 0 [Note] Binlog end
> 2020-06-05T20:18:36.355572Z 0 [Note] Shutting down plugin 'ngram'
> 2020-06-05T20:18:36.355590Z 0 [Note] Shutting down plugin 'partition'
> 2020-06-05T20:18:36.355596Z 0 [Note] Shutting down plugin 'BLACKHOLE'
> 2020-06-05T20:18:36.355602Z 0 [Note] Shutting down plugin 'ARCHIVE'
> 2020-06-05T20:18:36.355608Z 0 [Note] Shutting down plugin 'PERFORMANCE_SCHEMA'
> 2020-06-05T20:18:36.355648Z 0 [Note] Shutting down plugin 'MRG_MYISAM'
> 2020-06-05T20:18:36.355655Z 0 [Note] Shutting down plugin 'MyISAM'
> 2020-06-05T20:18:36.355665Z 0 [Note] Shutting down plugin 'INNODB_SYS_VIRTUAL'
> 2020-06-05T20:18:36.355670Z 0 [Note] Shutting down plugin 'INNODB_SYS_DATAFILES'
> 2020-06-05T20:18:36.355675Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLESPACES'
> 2020-06-05T20:18:36.355680Z 0 [Note] Shutting down plugin 'INNODB_SYS_FOREIGN_COLS'
> 2020-06-05T20:18:36.355686Z 0 [Note] Shutting down plugin 'INNODB_SYS_FOREIGN'
> 2020-06-05T20:18:36.355692Z 0 [Note] Shutting down plugin 'INNODB_SYS_FIELDS'
> 2020-06-05T20:18:36.355697Z 0 [Note] Shutting down plugin 'INNODB_SYS_COLUMNS'
> 2020-06-05T20:18:36.355702Z 0 [Note] Shutting down plugin 'INNODB_SYS_INDEXES'
> 2020-06-05T20:18:36.355707Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLESTATS'
> 2020-06-05T20:18:36.355712Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLES'
> 2020-06-05T20:18:36.355718Z 0 [Note] Shutting down plugin 'INNODB_FT_INDEX_TABLE'
> 2020-06-05T20:18:36.355723Z 0 [Note] Shutting down plugin 'INNODB_FT_INDEX_CACHE'
> 2020-06-05T20:18:36.355728Z 0 [Note] Shutting down plugin 'INNODB_FT_CONFIG'
> 2020-06-05T20:18:36.355733Z 0 [Note] Shutting down plugin 'INNODB_FT_BEING_DELETED'
> 2020-06-05T20:18:36.355738Z 0 [Note] Shutting down plugin 'INNODB_FT_DELETED'
> 2020-06-05T20:18:36.355743Z 0 [Note] Shutting down plugin 'INNODB_FT_DEFAULT_STOPWORD'
> 2020-06-05T20:18:36.355748Z 0 [Note] Shutting down plugin 'INNODB_METRICS'
> 2020-06-05T20:18:36.355753Z 0 [Note] Shutting down plugin 'INNODB_TEMP_TABLE_INFO'
> 2020-06-05T20:18:36.355758Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_POOL_STATS'
> 2020-06-05T20:18:36.355763Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_PAGE_LRU'
> 2020-06-05T20:18:36.355768Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_PAGE'
> 2020-06-05T20:18:36.355773Z 0 [Note] Shutting down plugin 'INNODB_CMP_PER_INDEX_RESET'
> 2020-06-05T20:18:36.355778Z 0 [Note] Shutting down plugin 'INNODB_CMP_PER_INDEX'
> 2020-06-05T20:18:36.355783Z 0 [Note] Shutting down plugin 'INNODB_CMPMEM_RESET'
> 2020-06-05T20:18:36.355788Z 0 [Note] Shutting down plugin 'INNODB_CMPMEM'
> 2020-06-05T20:18:36.355793Z 0 [Note] Shutting down plugin 'INNODB_CMP_RESET'
> 2020-06-05T20:18:36.355798Z 0 [Note] Shutting down plugin 'INNODB_CMP'
> 2020-06-05T20:18:36.355803Z 0 [Note] Shutting down plugin 'INNODB_LOCK_WAITS'
> 2020-06-05T20:18:36.355808Z 0 [Note] Shutting down plugin 'INNODB_LOCKS'
> 2020-06-05T20:18:36.355813Z 0 [Note] Shutting down plugin 'INNODB_TRX'
> 2020-06-05T20:18:36.355818Z 0 [Note] Shutting down plugin 'InnoDB'
> 2020-06-05T20:18:36.355930Z 0 [Note] InnoDB: FTS optimize thread exiting.
> 2020-06-05T20:18:36.356080Z 0 [Note] InnoDB: Starting shutdown...
> 2020-06-05T20:18:36.456533Z 0 [Note] InnoDB: Dumping buffer pool(s) to /var/lib/mysql/ib_buffer_pool
> 2020-06-05T20:18:36.456954Z 0 [Note] InnoDB: Buffer pool(s) dump completed at 200605 22:18:36
> 2020-06-05T20:18:37.765043Z 0 [Note] InnoDB: Shutdown completed; log sequence number 1213692
> 2020-06-05T20:18:37.765374Z 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
> 2020-06-05T20:18:37.765386Z 0 [Note] Shutting down plugin 'MEMORY'
> 2020-06-05T20:18:37.765396Z 0 [Note] Shutting down plugin 'CSV'
> 2020-06-05T20:18:37.765403Z 0 [Note] Shutting down plugin 'sha256_password'
> 2020-06-05T20:18:37.765408Z 0 [Note] Shutting down plugin 'mysql_native_password'
> 2020-06-05T20:18:37.765514Z 0 [Note] Shutting down plugin 'binlog'
> 2020-06-05T20:18:37.765737Z 0 [Note] mysqld: Shutdown complete

Then I don't get a new prompt (I waited once for more than an hour), but when I press enter I do...

I get some files in the mysql/var/lib/mysql folder:

>   0 auto.cnf    0 ib_buffer_pool  12M ibdata1  48M ib_logfile0  48M ib_logfile1    0 mysql

and in the mysql/var/lib/mysql/mysql folder (is this correct? A folder with the same name?)

> 512K db.frm     0 db.MYD     0 db.MYI     0 db.opt  512K func.frm     0 func.MYD     0 func.MYI  512K user.frm     0 user.MYD     0 user.MYI

The mysql/run/mysqld folder is empty.

I appreciate your help a lot!

**Comment by rgrandin** [comment]
Thanks.  I'll have to do some looking on this.  Did you start with a fresh `mysql` directory in this most-recent case?

**Comment by jw51** [comment]
Yes, I removed everything (that i could find in my working directory and home directory).

**Comment by rgrandin** [comment]
Great.  Thanks.

**Comment by rgrandin** [comment]
Sorry for the delayed response.  I can't replicate your issue, unfortunately, but perhaps you can provide me with a bit more info?

If you look at the Singularity file (https://github.com/ISU-HPC/mysql/blob/master/Singularity.5.7.21) you'll see, near the bottom, that the container is looking for the presence of the `/var/lib/mysql/mysql` directory (i.e., the directory containing data for the database "mysql").  The long output from the run command should say "Initializing mysqld" near the top, right after telling you that it is using the dot-files in your home directory.  Your output shows it skipping initialization and going straight to trying to run `mysqld` outright.  Naturally, this would fail if things hadn't been initialized.

So I'd like you to try 2 things.  First, repeat the steps like before, up through starting the instance.  Then, instead of using the run command, please run `singularity exec instance://mysql ls -alh /var/lib/mysql`.  I expect this to be an empty directory, though your above output is behaving as if there's already a mysql sub-folder.

Second, if there's a mysql sub-folder, can you list the contents? (`singularity exec instance://mysql ls -alh /var/lib/mysql/mysql`).  I'm not sure what would be putting that folder there before things are initialized.

I think you could possibly work around this by starting the instance like you have been, and then manually invoking the initialization command: `singularity exec instance://mysql mysqld --initialize  --init-file=${HOME}/.mysqlrootpw`).  Then try the final run command (`singularity run instance://mysql`).

**Comment by LoreVE** [comment]
Hi, sorry for the delayed response from my side. 

Running `singularity exec instance://mysql ls -alh /var/lib/mysql` returns `FATAL:   no instance found with name mysql`.  Running `singularity exec instance://mysql ls -alh /var/lib/mysql/mysql` returns `FATAL:  no instance found with name mysql`. So the /var/lib/mysql folder exists and is empty (no mysql folder inside).

After starting the instance and running the initialization command you suggested I get the following errors:
`2020-07-06T10:34:48.443986Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
mysqld: Can't create/write to file '/tmp/714f436e96/ibCHzAQ8' (Errcode: 2 - No such file or directory)
2020-07-06T10:34:48.484020Z 0 [ERROR] InnoDB: Unable to create temporary file; errno: 2
2020-07-06T10:34:48.484032Z 0 [ERROR] InnoDB: Plugin initialization aborted with error Generic error
2020-07-06T10:34:48.484041Z 0 [ERROR] Plugin 'InnoDB' init function returned error.
2020-07-06T10:34:48.484055Z 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
2020-07-06T10:34:48.484063Z 0 [ERROR] Failed to initialize builtin plugins.
2020-07-06T10:34:48.484068Z 0 [ERROR] Aborting`
...

**Comment by LoreVE** [comment]
Hi, sorry for the delayed response from my side.

Running `singularity exec instance://mysql ls -alh /var/lib/mysql` returns `FATAL: no instance found with name mysql`. Running `singularity exec instance://mysql ls -alh /var/lib/mysql/mysql` returns `FATAL: no instance found with name mysql`. So the /var/lib/mysql folder exists and is empty (no mysql folder inside).

After starting the instance and running the initialization command you suggested I get the following errors:

> 2020-07-06T10:34:48.443986Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
> mysqld: Can't create/write to file '/tmp/714f436e96/ibCHzAQ8' (Errcode: 2 - No such file or directory)
> 2020-07-06T10:34:48.484020Z 0 [ERROR] InnoDB: Unable to create temporary file; errno: 2
> 2020-07-06T10:34:48.484032Z 0 [ERROR] InnoDB: Plugin initialization aborted with error Generic error
> 2020-07-06T10:34:48.484041Z 0 [ERROR] Plugin 'InnoDB' init function returned error.
> 2020-07-06T10:34:48.484055Z 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
> 2020-07-06T10:34:48.484063Z 0 [ERROR] Failed to initialize builtin plugins.
> 2020-07-06T10:34:48.484068Z 0 [ERROR] Aborting
> ...

**Comment by jw51** [comment]
Hi, sorry for the delayed response from my side.

Running `singularity exec instance://mysql ls -alh /var/lib/mysql` returns `FATAL: no instance found with name mysql`. Running `singularity exec instance://mysql ls -alh /var/lib/mysql/mysql` returns `FATAL: no instance found with name mysql`. So the /var/lib/mysql folder exists and is empty (no mysql folder inside).

After starting the instance and running the initialization command you suggested I get the following errors:

> 2020-07-06T10:34:48.443986Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
> mysqld: Can't create/write to file '/tmp/714f436e96/ibCHzAQ8' (Errcode: 2 - No such file or directory)
> 2020-07-06T10:34:48.484020Z 0 [ERROR] InnoDB: Unable to create temporary file; errno: 2
> 2020-07-06T10:34:48.484032Z 0 [ERROR] InnoDB: Plugin initialization aborted with error Generic error
> 2020-07-06T10:34:48.484041Z 0 [ERROR] Plugin 'InnoDB' init function returned error.
> 2020-07-06T10:34:48.484055Z 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
> 2020-07-06T10:34:48.484063Z 0 [ERROR] Failed to initialize builtin plugins.
> 2020-07-06T10:34:48.484068Z 0 [ERROR] Aborting

...

**Comment by rgrandin** [comment]
Can you please start fresh, then start the instance, and then `singularity exec instance://mysql ls -alh /var/lib/mysql` and `singularity exec instance://mysql ls -alh /var/lib/mysql/mysql`?  In your last reply the error message you show (`FATAL: no instance found with name mysql`) indicates that the instance wasn't running, so the `ls` commands weren't able to tell us anything.

Please also run 1 more command within the instance: `singularity exec instance://mysql whoami`.  I want to see how the permissions on the directory compares to the user you are running as within the container instance.

**Comment by marco91sol** [comment]
I have a quite similar problem. 

I tried with:

```
singularity exec instance://mysql whoami
myuser
```
However, if I try to run the instance with the command: 

`singularity` run instance://mysql`

I obtain the following error:
![image](https://user-images.githubusercontent.com/42739946/131673405-88bade6a-6222-4328-8609-4cbc2c144031.png)

But, I used the commands explained as explained in your repo. 

Thanks,
Marco

**Comment by rgrandin** [comment]
Do you have something running that is already using port 3306, as noted by the error message?

**Comment by marco91sol** [comment]
Nothing running on it.

**Comment by rgrandin** [comment]
As I asked the first user in this thread, can you please start fresh and follow the instructions here: https://www.hpc.iastate.edu/guides/containers/mysql-server.  Then, please copy/paste the output from each step so I can see what is happening.  When starting fresh, please double-check that you are using a clean data directory (no cruft leftover from an earlier failed attempt).  Also check that  you don't have any other singularity containers running so that there's nothing to get in the way.

**Comment by marco91sol** [comment]
I launched this : 

```
singularity instance.start --bind ${HOME} \
    --bind ${PWD}/mysql/var/lib/mysql/:/var/lib/mysql \
    --bind ${PWD}/mysql/run/mysqld:/run/mysqld \
    ./mysql.simg mysql
```
The output: 
**INFO:    instance started successfully**

I checked the list of instances: 

**INSTANCE NAME    PID      IP              IMAGE
mysql            2388294                  /mnt/DATA/home/marcos/mysql.simg**

Then, when I run `singularity run instance://mysql` , it gives me the following output: 

> 2021-09-02T12:49:42.520670Z 0 [Note] mysqld (mysqld 5.7.21) starting as process 87 ...
> 2021-09-02T12:49:42.526820Z 0 [Note] InnoDB: PUNCH HOLE support available
> 2021-09-02T12:49:42.526858Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
> 2021-09-02T12:49:42.526868Z 0 [Note] InnoDB: Uses event mutexes
> 2021-09-02T12:49:42.526877Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
> 2021-09-02T12:49:42.526885Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.3
> 2021-09-02T12:49:42.527400Z 0 [Note] InnoDB: Number of pools: 1
> 2021-09-02T12:49:42.527615Z 0 [Note] InnoDB: Using CPU crc32 instructions
> 2021-09-02T12:49:42.530728Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
> 2021-09-02T12:49:42.548244Z 0 [Note] InnoDB: Completed initialization of buffer pool
> 2021-09-02T12:49:42.552867Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man
>  page of setpriority().
> 2021-09-02T12:49:42.566444Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
> 2021-09-02T12:49:42.579512Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
> 2021-09-02T12:49:42.579662Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
> 2021-09-02T12:49:42.598452Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
> 2021-09-02T12:49:42.601232Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
> 2021-09-02T12:49:42.601250Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
> 2021-09-02T12:49:42.601785Z 0 [Note] InnoDB: 5.7.21 started; log sequence number 2551185
> 2021-09-02T12:49:42.601943Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
> 2021-09-02T12:49:42.602242Z 0 [Note] Plugin 'FEDERATED' is disabled.
> 2021-09-02T12:49:42.604945Z 0 [Note] InnoDB: Buffer pool(s) load completed at 210902 14:49:42
> 2021-09-02T12:49:42.610379Z 0 [Warning] Failed to set up SSL because of the following SSL library error: SSL context is not usable without certif
> icate and private key
> 2021-09-02T12:49:42.611009Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
> 2021-09-02T12:49:42.611163Z 0 [Note] IPv6 is available.
> 2021-09-02T12:49:42.611183Z 0 [Note]   - '::' resolves to '::';
> 2021-09-02T12:49:42.611272Z 0 [Note] Server socket created on IP: '::'.
> 2021-09-02T12:49:42.611308Z 0 [ERROR] Can't start server: Bind on TCP/IP port: Address already in use
> 2021-09-02T12:49:42.611313Z 0 [ERROR] Do you already have another mysqld server running on port: 3306 ?
> 2021-09-02T12:49:42.611324Z 0 [ERROR] Aborting
> 
> 2021-09-02T12:49:42.611335Z 0 [Note] Binlog end
> 2021-09-02T12:49:42.611389Z 0 [Note] Shutting down plugin 'ngram'
> 2021-09-02T12:49:42.611398Z 0 [Note] Shutting down plugin 'partition'
> 2021-09-02T12:49:42.611403Z 0 [Note] Shutting down plugin 'BLACKHOLE'
> 2021-09-02T12:49:42.611408Z 0 [Note] Shutting down plugin 'ARCHIVE'
> 2021-09-02T12:49:42.611413Z 0 [Note] Shutting down plugin 'PERFORMANCE_SCHEMA'
> 2021-09-02T12:49:42.611472Z 0 [Note] Shutting down plugin 'MRG_MYISAM'
> 2021-09-02T12:49:42.611477Z 0 [Note] Shutting down plugin 'MyISAM'
> 2021-09-02T12:49:42.611495Z 0 [Note] Shutting down plugin 'INNODB_SYS_VIRTUAL'
> 2021-09-02T12:49:42.611500Z 0 [Note] Shutting down plugin 'INNODB_SYS_DATAFILES'
> 2021-09-02T12:49:42.611505Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLESPACES'
> 2021-09-02T12:49:42.611510Z 0 [Note] Shutting down plugin 'INNODB_SYS_FOREIGN_COLS'
> 2021-09-02T12:49:42.611514Z 0 [Note] Shutting down plugin 'INNODB_SYS_FOREIGN'
> 2021-09-02T12:49:42.611519Z 0 [Note] Shutting down plugin 'INNODB_SYS_FIELDS'
> 2021-09-02T12:49:42.611524Z 0 [Note] Shutting down plugin 'INNODB_SYS_COLUMNS'
> 2021-09-02T12:49:42.611529Z 0 [Note] Shutting down plugin 'INNODB_SYS_INDEXES'
> 2021-09-02T12:49:42.611534Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLESTATS'
> 2021-09-02T12:49:42.611548Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLES'
> 2021-09-02T12:49:42.611553Z 0 [Note] Shutting down plugin 'INNODB_FT_INDEX_TABLE'
> 2021-09-02T12:49:42.611558Z 0 [Note] Shutting down plugin 'INNODB_FT_INDEX_CACHE'
> 2021-09-02T12:49:42.611563Z 0 [Note] Shutting down plugin 'INNODB_FT_CONFIG'
> 2021-09-02T12:49:42.611568Z 0 [Note] Shutting down plugin 'INNODB_FT_BEING_DELETED'
> 2021-09-02T12:49:42.611572Z 0 [Note] Shutting down plugin 'INNODB_FT_DELETED'
> 2021-09-02T12:49:42.611577Z 0 [Note] Shutting down plugin 'INNODB_FT_DEFAULT_STOPWORD'
> 2021-09-02T12:49:42.611582Z 0 [Note] Shutting down plugin 'INNODB_METRICS'
> 2021-09-02T12:49:42.611586Z 0 [Note] Shutting down plugin 'INNODB_TEMP_TABLE_INFO'
> 2021-09-02T12:49:42.611591Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_POOL_STATS'
> 2021-09-02T12:49:42.611596Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_PAGE_LRU'
> 2021-09-02T12:49:42.611600Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_PAGE'
> 2021-09-02T12:49:42.611605Z 0 [Note] Shutting down plugin 'INNODB_CMP_PER_INDEX_RESET'
> 2021-09-02T12:49:42.611610Z 0 [Note] Shutting down plugin 'INNODB_CMP_PER_INDEX'
> 2021-09-02T12:49:42.611615Z 0 [Note] Shutting down plugin 'INNODB_CMPMEM_RESET'
> 2021-09-02T12:49:42.611619Z 0 [Note] Shutting down plugin 'INNODB_CMPMEM'
> 2021-09-02T12:49:42.611624Z 0 [Note] Shutting down plugin 'INNODB_CMP_RESET'
> 2021-09-02T12:49:42.611629Z 0 [Note] Shutting down plugin 'INNODB_CMP'
> 2021-09-02T12:49:42.611633Z 0 [Note] Shutting down plugin 'INNODB_LOCK_WAITS'
> 2021-09-02T12:49:42.611638Z 0 [Note] Shutting down plugin 'INNODB_LOCKS'
> 2021-09-02T12:49:42.611643Z 0 [Note] Shutting down plugin 'INNODB_TRX'
> 2021-09-02T12:49:42.611647Z 0 [Note] Shutting down plugin 'InnoDB'
> 2021-09-02T12:49:42.611736Z 0 [Note] InnoDB: FTS optimize thread exiting.
> 2021-09-02T12:49:42.611826Z 0 [Note] InnoDB: Starting shutdown...
> 2021-09-02T12:49:42.712073Z 0 [Note] InnoDB: Dumping buffer pool(s) to /var/lib/mysql/ib_buffer_pool
> 2021-09-02T12:49:42.712431Z 0 [Note] InnoDB: Buffer pool(s) dump completed at 210902 14:49:42
> 2021-09-02T12:49:44.021355Z 0 [Note] InnoDB: Shutdown completed; log sequence number 2551204
> 2021-09-02T12:49:44.024768Z 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
> 2021-09-02T12:49:44.024789Z 0 [Note] Shutting down plugin 'MEMORY'
> 2021-09-02T12:49:44.024798Z 0 [Note] Shutting down plugin 'CSV'
> 2021-09-02T12:49:44.024806Z 0 [Note] Shutting down plugin 'sha256_password'
> 2021-09-02T12:49:44.024813Z 0 [Note] Shutting down plugin 'mysql_native_password'
> 2021-09-02T12:49:44.025105Z 0 [Note] Shutting down plugin 'binlog'
> 2021-09-02T12:49:44.025434Z 0 [Note] mysqld: Shutdown complete

Thanks for your support!

**Comment by rgrandin** [comment]
Thanks for the detail.  Sorry for the delay in my response.

Can you please verify that you don't have something already using port 3306?  A few commands you can try:
* `ss -tlnp | grep 3306` will show you if a port is used
* `sudo ss -tlnp | grep 3306` will identify the actual process using that port (note the `sudo`)
* `sudo lsof -i TCP:3306` will also identify which process is using that port

**Comment by rgrandin** [comment]
I'm going to close this issue due to lack of activity.
